Fix wart that scalafmt will reformt `behavior of` in scalatest.
scalameta/scalafmt pull request #2252
Opened 2020-10-29 17:38 UTC by sequencer

In scalatest, scala format will reformat:
```diff
- behavior of "something"
+ behavior.of("something")
```
This patch will fix this.

2020-10-29 19:17 UTC, poslegm commented
Hello! Not sure about default for this word. You can just specify some filters you want in your `.scalafmt.conf`:

```
rewrite.neverInfix.excludeFilters = [
  until
  to
  by
  eq
  ne
  "should.*"
  "contain.*"
  "must.*"
  in
  ignore
  be
  taggedAs
  thrownBy
  synchronized
  have
  when
  size
  only
  noneOf
  oneElementOf
  noElementsOf
  atLeastOneElementOf
  atMostOneElementOf
  allElementsOf
  inOrderElementsOf
  theSameElementsAs
  of
  include
]
```

Why is this method not suitable for you?

2020-10-30 20:29 UTC, kitbellew commented
here's an example of the config we use:

```
rewrite {
  rules = [
    AvoidInfix,
    ...
  ]
  neverInfix.excludeFilters = [
    until
    to
    by
    eq
    ne
    synchronized
  ]
}

fileOverride {
  "glob:**/{test,it,src/test/scala}/{*.scala,**/*.scala}" {
    rewrite.neverInfix.excludeFilters = [
      until
      to
      by
      eq
      ne
      "should.*"
      "contain.*"
      "must.*"
      in
      ignore
      be
      of
      message
      taggedAs
      thrownBy
      synchronized
      have
      when
      size
      only
      noneOf
      "one.*Of"
      "atLeast.*Of"
      "atMost.*Of"
      "all.*Of"
      noElementsOf
      "inOrder.*"
      "theSame.*As"
      length
      regex
      key
      include
      and
      or
    ]
  }
}
```

2020-10-31 11:03 UTC, sequencer commented
Thanks! I see, I wonder maybe I can try to upstream the keywords in scalatest? Maybe that will be usefull?

2020-10-31 13:35 UTC, kitbellew commented
> Thanks! I see, I wonder maybe I can try to upstream the keywords in scalatest? Maybe that will be usefull?

What do you mean by "upstream" here?

2020-10-31 13:36 UTC, kitbellew requested changes
Discussing as a config change

2020-10-31 16:05 UTC, sequencer commented
> What do you mean by "upstream" here?
Yes I think scalatest is widely used, and it's elements in `neverInfix` are already scalatest keywords. 
So maybe complement it would be better.

2020-10-31 16:33 UTC, kitbellew commented
> > What do you mean by "upstream" here?
> 
> Yes I think scalatest is widely used, and it's elements in `neverInfix` are already scalatest keywords.
> So maybe complement it would be better.

the problem is, some of scalatest's keywords are also popular methods (such as size, in, etc.; for instance, in spark functions), and i don't think they should be formatted as infix. scalatest exceptions should only be applied to test code.

2020-10-31 17:16 UTC, sequencer commented
I see, that's sound reasonable!
I'll use @poslegm's solution to override!

2020-10-31 17:16 UTC, closed without merging