[Scala 3] Allow to use commas instead of with for multiple parents
scalameta/scalafmt pull request #2326
Opened 2021-01-13 13:51 UTC by tgodzik

Scala 3 allows for using `,` instead of `with` when declaring multiple parents.

2021-01-13 15:10 UTC, kitbellew requested changes
lots of good tests 🙂

2021-01-13 15:38 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
> +        val ident = if (isFirstParent(template, prevOwner)) 2 else 0
It looked more natural to have it as a default:
```scala
class A
  extends B,
    C,
    D
```

than
```
class A
  extends B,
  C,
  D
```

I can add it as a new setting maybe with a default of 2?

2021-01-13 15:44 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
> +        val prevOwner = prev(formatToken).meta.leftOwner
The alternative I thought of was to find if the `rightOwner` is a second `Init`, but that would be a separate method and it seemed better to reuse an existing one.

Also, this already works with `with`, where we use the `leftOwner` which is essentially the owner of the token before with. With `prevOwner` we are doing exactly the same, prevOwner is the owner of the token before `,` which replaces `with`  

The only problem might be with a `Comment` I guess. I could:
- create a separate method that checks if the leftOWner is the secondInit
- or just handle comment before `,`

what do you think?

2021-01-13 15:49 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
> +        val prevOwner = prev(formatToken).meta.leftOwner
The comment case is also broken currently actually. We will get:
```scala
class A
    extends AVeryLongName1 /* asfgf */
    with AVeryLongName2
    with AVeryLongName3
```

despite setting `continuationIndent.withSiteRelativeToExtends = 2`

2021-01-13 15:53 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
> +              if !hasSelfAnnotation &&
I copied that one, though I am not sure if it's always true. Why do you say that? `hasSelfAnnotation` might be false or true, which will change the entire condition.

2021-01-13 16:01 UTC, kitbellew commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
> +        val prevOwner = prev(formatToken).meta.leftOwner
i never looked at this case before but it would be good to fix it, perhaps now or later

2021-01-13 16:02 UTC, kitbellew commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
> +              if !hasSelfAnnotation &&
a few lines above, we checked this flag, so now it's known.

2021-01-13 16:06 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
> +              if !hasSelfAnnotation &&
Ach, right! Good catch!

2021-01-14 17:19 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
> +        val ident = if (isFirstParent(template, prevOwner)) 2 else 0
Added `commaSiteRelativeToExtends`.

2021-01-14 17:38 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
> +  ) = {
Fixed.

2021-01-14 17:38 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
> +              if !hasSelfAnnotation &&
Removed it!

2021-01-14 17:39 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/util/TreeOps.scala
> +  def isFirstParent(t: Template, owner: Tree) =
Changed to `isFirstInit`

2021-01-14 17:39 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
> +      // trait A extends B, C, D, E
Removed empty lines, they are not needed here I think.

2021-01-14 17:39 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Router.scala
> +        val prevOwner = prev(formatToken).meta.leftOwner
Fixed it and added test cases for both `with` and commas

2021-01-14 17:57 UTC, kitbellew requested changes

2021-01-14 17:57 UTC, kitbellew commented on scalafmt-core/shared/src/main/scala/org/scalafmt/config/ContinuationIndent.scala
> +  * @param comaSiteRelativeToExtends additional indentation before in the line after extends with a coma
Typo

2021-01-14 17:57 UTC, kitbellew commented on scalafmt-tests/src/test/resources/scala3/ExtendsComma.stat
> +      AVeryLongName3
Eol

2021-01-14 17:57 UTC, kitbellew commented on scalafmt-tests/src/test/resources/test/ContinuationIndent.stat
> +    with AVeryLongName2
Eol

2021-01-14 18:15 UTC, tgodzik commented on scalafmt-tests/src/test/resources/test/ContinuationIndent.stat
> +    with AVeryLongName2
Fixed.

2021-01-14 18:15 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/config/ContinuationIndent.scala
> +  * @param comaSiteRelativeToExtends additional indentation before in the line after extends with a coma
Fixed, thanks!

2021-01-14 18:15 UTC, tgodzik commented on scalafmt-tests/src/test/resources/test/ContinuationIndent.stat
> +    with AVeryLongName2
Fixed!

2021-01-14 18:15 UTC, tgodzik commented on scalafmt-tests/src/test/resources/scala3/ExtendsComma.stat
> +      AVeryLongName3
Fixed!

2021-01-14 18:23 UTC, kitbellew approved these changes

2021-01-14 18:26 UTC, merged