Allow optional braces after old style while and for
scalameta/scalafmt pull request #2791
Opened 2021-10-06 10:34 UTC by tgodzik

Fixes https://github.com/scalameta/scalafmt/issues/2790

2021-10-06 14:15 UTC, kitbellew requested changes

2021-10-06 14:15 UTC, kitbellew commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
> +          case Term.For(_, t: Term.Block)
looks like we now have extra conditions. is that equivalent? keep in mind that right brace method may have been used not just for formatting but for rewrite, maybe end marker, and possibly something else. can we do a quick search on usage of `rightBrace` and see if there are cases we'd forgotten to cover with tests?

2021-10-06 14:15 UTC, kitbellew commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
> -              def splits = None
in #2420, the last comment talks about following up with "for" and "while" after fixing in the parser, perhaps we simply never did.

2021-10-06 14:15 UTC, kitbellew commented on scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
> +  for (scene <- scenes.all)
can you add another loop with a single statement in the body? it looks like plain old scala2 code and should not use significant indentation. same with while.

2021-10-06 14:15 UTC, kitbellew commented on scalafmt-tests/src/test/resources/scala3/OptionalBraces.stat
> +  val s = stateModifier(currentState, tpf)
optional: i don't think we need these three lines. just the loops is probably enough.

2021-10-06 14:53 UTC, tgodzik commented on scalafmt-core/shared/src/main/scala/org/scalafmt/internal/FormatOps.scala
> -              def splits = None
Och, that might be right :sweat_smile:

2021-10-18 16:59 UTC, kitbellew commented
Submitted in #2803.

2021-10-18 16:59 UTC, closed without merging