Build arm64 docker image
scalameta/scalafmt pull request #4101
Opened 2024-07-11 02:23 UTC by harryzcy

2024-07-11 03:00 UTC, kitbellew requested changes
it seems to me that you're trying to introduce an alternative to the existing process. can you please suggest a way to reuse it instead?

please take a look at the following to see if you can accomplish that:
- https://github.com/scalameta/scalafmt/blob/master/bin/build-native-image.sh
- https://github.com/scalameta/scalafmt/blob/master/project/plugins.sbt
- https://github.com/scalameta/sbt-native-image

2024-07-11 03:22 UTC, kitbellew commented
one other point: `ci` workflow simply checks whether a new commit is valid. if you want to have an image to install, i'd expect it to be published in `release` workflow.

@tgodzik would you be able to confirm that?

2024-07-11 04:12 UTC, harryzcy commented
> it seems to me that you're trying to introduce an alternative to the existing process. can you please suggest a way to reuse it instead?

I'm reusing `bin/build-native-image.sh` here.

```
RUN microdnf install -y git \
  && bin/build-native-image.sh \
  && mv scalafmt-cli/target/native-image/cli /bin/scalafmt
```

Does sbt-native-image only work with Java 8 and Java 11? The [`sbtscala/scala-sbt` image](https://hub.docker.com/r/sbtscala/scala-sbt/tags) only offers arm64 for Java 17, and I'm having issues building it

2024-11-19 09:27 UTC, kitbellew commented
@harryzcy would you like to retry this effort, now that #4561 has been merged?

2025-01-13 14:28 UTC, aairey commented
Seems docker-login is failing during CI?
@harryzcy can you rebase this PR?

2025-02-11 07:32 UTC, harryzcy commented
Closing in favor of https://github.com/scalameta/scalafmt/pull/4802

2025-02-11 07:32 UTC, closed without merging